// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using botplatform.Models.pmprocessor.db_storage;

#nullable disable

namespace botplatform.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240518192024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("botplatform.Models.pmprocessor.db_storage.User", b =>
                {
                    b.Property<long>("tg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ln")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("un")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("tg_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
